require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7.1
  TargetRailsVersion: 7.0
  Include:
    -  'app/**/*'
    - 'config.ru'
    - 'Gemfile'
    - 'Guardfile'
    - 'Rakefile'
  Exclude:
    - 'app/views/**/*'
    - 'app/assets/**/*'
    - 'app/javascript/**/*'
    - 'bin/*'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'log/**/*'
    - 'node_modules/**/*'
    - 'public/**/*'
    - 'scripts/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - '.git/**/*'
    - 'spec/**/*'

Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'Guardfile'

Naming/FileName:
  Exclude:
    - 'Gemfile'
    - 'Guardfile'
    - 'Rakefile'

Rails:
  Enabled: true

